# Generated by Django 4.2.6 on 2023-10-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_rename_post_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.ManyToManyField(to='blog_app.author'),
        ),
    ]
