# Generated by Django 4.2.6 on 2023-10-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_remove_blogpost_author_blogpost_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.ManyToManyField(blank=True, null=True, related_name='blog_author', to='blog_app.author'),
        ),
    ]
